// figure this one out champ?
module.exports = {
    name: 'wutang',
    description: 'For da children',
    execute(msg, args) {
        const wu_tang_lyrics = [
          'Ghostface catch the blast of a hype verse\nMy Glock burst, leave in a hearse, I did worse',
          'Aww shit, Wu-Tang Clan spark the wicks, an\'\nHowever I master the trick just like Nixon',
          'Causin\' terror, quick damage your whole era\nHard rocks is locked the fuck up, or found shot',
          'I watch my back like I\'m locked down\nHardcore-hittin\' soundn\nWatch me act bugged and tear down\nIlliterate-type asshole, songs goin\' gold',
          'Yeah, they fake and all that, carryin\' gats\nBut yo, my Clan rollin\' like forty macks\nNow you act convinced, I guess it makes sense\nWu-Tang, yo, soooo represent!',
          'And that\'s one in the chamber, Wu-Tang banger\n36 styles of danger',
          'I rip it hardcore, like porno-flick bitches\nI roll with groups of ghetto bastards with biscuits',
          'Check it, my method on the microphone\'s bangin\'\nWu-Tang slang\'ll leave your headpiece hangin\'',
          'Redrum, I verbally assault with the tongue\nMurder One, my style shocks your knot like a stun gun',
          'Set it on the microphone, and competition get blown\nBy this nasty-ass nigga with my nigga, the RZA\nCharged like a bull and got pulled like a trigga\nSo bad, stabbin\' up the pad with the vocab, crab\nI scream on your ass like your dad, bring it on...',
          'Yo, I\'m more rugged than slave man boots\nNew recruits, I\'m fuckin\' up MC troops\nI break loose, and trample shit, while I stomp\nA mudhole in that ass \'cause I\'m straight out the swamp',
          'I blow up his fuckin\' prism, make it a vicious act of terrorism\nYou wanna bring it, so fuck it, come on and bring the ruckus!',
          'En garde, I\'ll let you try my Wu-Tang style.',
          'Shame on a nigga who try to run game on a nigga\nWu buck wild with the trigger',
          'Shame on a nigga who try to run game on a nigga\nWu buck… I\'ll fuck your ass up!',
          'Ol\' Dirty Bastard, live and uncut\nStyles unbreakable, shatterproof\nTo the young youth, you wanna get gun? Shoot!\nBlaow! How you like me now?',
          'Don\'t fuck the style, ruthless wild\nDo you wanna get your teeth knocked the fuck out?\nWanna get on it like that? Well, then shout!',
          'Yo RZA, yo razor, hit me with the major\nThe damage, my Clan understand it be flavor\nGunnin\', hummin\', comin\' at ya First I\'m gonna get ya, once I got ya, I gat ya',
          'You could never capture the Method Man\'s stature\nFor rhyme and for rapture, got niggas resignin\', now master\nMy style? Never!',
          'I put the fuckin\' buck in the wild kid, I\'m terror, razor sharp, I sever\nThe head from the shoulders, I\'m better than my competta\nYou mean competitor, whatever, let\'s get together',
          'So, when you see me on the real\nFormin\' like Voltron, remember I got deep like a Navy Seal',
          'Burn me, I get into shit, I let it out like diarrhea\nGot burnt once but that was only gonorrhea',
          'The Wu is comin\' through, the outcome is critical\nFuckin\' with my style is sort of like a miracle',
          '\'Cause I don\'t know you, therefore show me what you know\nI come sharp as a blade and I cut you slow',
          'You become so Pat as my style increases\nWhat\'s that in your pants? Ahh, human feces!\nThrow your shitty drawers in the hamper\nNext time, come strapped with a fuckin\' Pamper',
          'Can it be that it was all so simple then?\nDedicated to the 5\'s, 850i\'s\n(Dedicated to niggas who do drive-by\'s)',
          'Raw I\'ma give it to ya, with no trivia\nRaw like cocaine straight from Bolivia',
          'Well, I\'m a sire, I set the microphone on fire\nRap styles vary and carry like Mariah',
          'I come from the Shaolin slum, and the isle I\'m from\nIs comin\' through with nuff niggas and nuff guns\nSo if you wanna come sweatin\', stressin\', contestin\'\nYou\'ll catch a sharp sword to the midsection',
          'Rough like Timberland wear, yeah\nMe and the Clan in \'Yota Landcruisers out there\nPeace to all the crooks, all the niggas with bad looks\nBald heads, braids, blow this hook',
          'I only been a good nigga for a minute though\n\'Cause I got to get my props and win it, yo',
          'I got beef with commercial-ass niggas with gold teeth\nLampin\' in a Lexus, eatin\' beef\nStraight up and down, don\'t even bother\nI got 40 niggas up in here now who kill niggas\' fathers',
          'My peoples, are you with me? Where you at?\nIn the front, in the back, Killa Bees on attack',
          'My peoples, are you with me? Where you at?\nSmokin\' meth, hittin\' cats on the block with the gats',
          'Homicide\'s illegal and death is the penalty\nOne justifies the homicide when he dies in his own iniquity?',
          'The flow changes like a chameleon\nPlays like a friend and stabs you like a dagger\nThis technique attacks the immune system\nDisguised like a lie, paralyzin\' the victim',
          'You scream as it enters your bloodstream\nErupts your brain from the pain these thoughts contain\nMovin\' on a nigga with the speed of a centipede\nAnd injure any motherfuckin\' contender',
          'And the survey said you\'re dead\nFatal Flying Guillotine chops off your fuckin\' head',
          'And if you want beef, then bring the ruckus!\n Wu-Tang Clan ain\'t nuthing ta fuck wit',
          'Straight from the motherfuckin\' slums that\'s busted\nWu-Tang Clan ain\'t nuthing ta fuck wit',
          'Like déjà vu, I\'m rubber, niggas is like glue\nWhatever you say rubs off me sticks to you',
          'I grew up on the crime side, the New York Times side\n Stayin\' alive was no jive',
          'But it was just a dream for the teen who was a fiend\nStarted smokin\' woolies at 16',
          'No question I would speed for cracks and weed\nThe combination made my eyes bleed',
          'No question I would flow off and try to get the dough all\nStickin\' up white boys in ball courts',
          'Cash rules everything around me\nC.R.E.A.M., get the money\nDollar dollar bill, y\'all',
          'A man with a dream with plans to make cream\nWhich failed; I went to jail at the age of fifteen\nA young buck sellin\' drugs and such, who never had much\nTryin\' to get a clutch at what I could not',
          'The court played me short, now I face incarceration\nPacin\', goin\' upstate\'s my destination\nHandcuffed in the back of a bus, forty of us Life as a shorty shouldn\'t be so rough',
          'But as the world turned I learned life is hell\nLivin\' in the world no different from a cell',
          'But shorty\'s runnin\' wild, smokin\' sess, drinkin\' beer\n And ain\'t tryin\' to hear what I\'m kickin\' in his ear\nNeglected for now, but yo, it gots to be accepted\nThat what? That life is hectic',
          'I smoke on the mic like "Smokin\' Joe" Frazier\n The hell-raiser, raisin\' hell with the flavor',
          'Terrorize the jam like troops in Pakistan\n Swingin\' through your town like your neighborhood Spider-Man',
          'Call me the rap assassinator\nRhymes rugged and built like Schwarzenegger',
          'It\'s the Method Man, for short Mr. Mef\nMovin\' on your left, UH!',
          'And set it off, get it off, let it off like a gat\nI wanna break, fool, cock me back',
          'First things first, man, you\'re fuckin\' with the worst\nI\'ll be stickin\' pins in your head like a fuckin\' nurse',
          'Niggas be rollin\' with a stash, ain\'t sayin\' cash\nBite my style, I\'ll bite your motherfuckin\' ass',
          'Crazy flamboyant for the rap enjoyment\nMy clan increase like black unemployment',
          'The Wu is too slammin\' for these Cold Killin\' labels\nSome ain\'t had hits since I seen Aunt Mabel\nBe doin\' artists in like Cain did Abel\nNow they money\'s gettin\' stuck to the gum under the table',
          'Now that thought was just as bright as a 20-watt light bulb\nShould\'ve pumped it when I rocked it\nNiggas so stingy they got short arms and deep pockets'
      ]
        const randomAnswer = wu_tang_lyrics[Math.floor(Math.random() * wu_tang_lyrics.length)];
        msg.channel.send(randomAnswer);
    }
}
